blank_issues_enabled: false
contact_links:
  - name: ðŸ™‹ Ask a Question
    url: https://github.com/grid-kitchen/grid-reducer/discussions
    about: Ask a question or get help with using grid-reducer